# Generated by Django 3.0.7 on 2020-12-14 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCalculatedDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField(max_length=10)),
                ('total_shares', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('avg_net_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField(max_length=10)),
                ('name', models.TextField(max_length=100)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_date', models.DateTimeField(null=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('last_updated_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('portfolio',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_stock',
                                   to='portfolio.Portfolio')),
            ],
        ),
    ]
