# Generated by Django 2.1.7 on 2020-01-07 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField(max_length=10)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_stock', to='portfolio.Portfolio')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('portfolio', 'symbol')},
        ),
    ]
