# Generated by Django 3.0.7 on 2020-10-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200628_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCalculatedDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField(max_length=10)),
                ('total_shares', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('avg_net_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='sold_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
    ]
