# Generated by Django 3.0.7 on 2020-11-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20201026_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
