# Generated by Django 3.0.7 on 2020-11-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20201115_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='last_updated_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
    ]
