# Generated by Django 3.0.7 on 2020-11-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20201115_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='isarchived',
            field=models.BooleanField(null=True),
        ),
    ]
