# Generated by Django 2.1.7 on 2020-01-07 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shares', models.IntegerField(default=0)),
                ('fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_updated_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('stock',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transaction',
                                   to='stock.Stock')),
            ],
        ),
    ]
