# Generated by Django 3.0.7 on 2021-01-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_default',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
