# Generated by Django 3.0.7 on 2020-12-14 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sold_date', models.DateTimeField(null=True)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_status', to='plan.PlanStatus')),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_plan', to='stock.Stock')),
            ],
        ),
    ]
