# Generated by Django 3.0.7 on 2021-02-07 02:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='sold_date',
        ),
    ]
